<script setup lang="ts">
import { computed, ref } from 'vue';
import { useLinkedRecords, choiceName } from '../linkedRecords';
import { makeStore } from '../setupCatalogs';
import { useMysqlRecords } from '../useMysqlRecords';
import { validAgencyExtra } from '../agencyExtras';
import { currencyCodes } from '../currencies';
import { newProposal, newProposalLine, proposalStatuses, today, useProposals, type Proposal, type ProposalLine, type ProposalKind } from '../proposals';
import { nightsBetween, lineAmount, proposalTotals } from '../proposalMath.mjs';
import ProposalFields, { type FormField } from './ProposalFields.vue';
import VoxActionButton from './VoxActionButton.vue';
import { voxConfirm } from '../voxDialogs';
const props=defineProps<{kind:ProposalKind;userName:string}>();
const store=useProposals(props.kind), linked=useLinkedRecords(), citizens=makeStore('citizens'), markets=makeStore('markets');
const agencyExtras=useMysqlRecords('agency-extras',[],validAgencyExtra);
const draft=ref<Proposal|null>(null), line=ref<ProposalLine|null>(null), form=ref<HTMLFormElement|null>(null), message=ref('');
const query=ref(''), filter=ref('active');
const title=computed(()=>({'golf':'Golf Teklifleri','hotel':'Otel Teklifleri','hotel-golf':'Otel + Golf Teklifleri'})[props.kind]);
const agencyName=(key:string)=>choiceName(linked.agencyChoices.value,key);
const hotelName=(key:string)=>choiceName(linked.hotelChoices.value,key);
const courseName=(key:string)=>choiceName(linked.courseChoices.value,key);
const identity=(r:any)=>String(r.id??r.code);
const options=(rows:any[])=>rows.map(r=>({id:identity(r),name:r.name??r.fields?.[0]}));
const simple=(values:string[])=>values.map(v=>({id:v,name:v}));
const selectedHotel=computed(()=>linked.hotels.records.value.find(r=>String(r.id)===line.value?.hotel));
const roomOptions=computed(()=>linked.rooms.records.value.find(r=>identity(r)===line.value?.roomType)?.children?.filter(r=>!r.hotel||r.hotel===selectedHotel.value?.name)??[]);
const dateMatches=(r:any)=>!!line.value?.firstDate&&r.firstDate<=line.value.firstDate&&r.lastDate>=line.value.lastDate;
const golfTariffs=computed(()=>linked.contracts.records.value.filter(r=>r.courseKey===line.value?.course&&r.status==='ACTIVE'&&dateMatches(r)));
const hotelContracts=computed(()=>selectedHotel.value?.details?.contracts?.filter(r=>r.status==='ACTIVE'&&dateMatches(r))??[]);
const packages=computed(()=>selectedHotel.value?.details?.packages?.filter(r=>r.status==='ACTIVE'&&dateMatches(r))??[]);
const hotelContract=computed(()=>hotelContracts.value.find(r=>r.id===line.value?.hotelContract));
const selectedPackage=computed(()=>packages.value.find(r=>r.id===line.value?.packageId));
const prices=computed(()=>line.value?.category==='hotel-golf'?(selectedPackage.value?.rounds??[]).filter(r=>r.accommodation===line.value?.accommodation):hotelContract.value?.prices??[]);
const extraOptions=computed(()=>[
 ...(selectedHotel.value?.details?.extras??[]).filter(dateMatches).map(r=>({...r,id:'hotel:'+r.id})),
 ...agencyExtras.records.value.filter(r=>r.agencyKey===draft.value?.agency&&dateMatches(r)).map(r=>({...r,id:'agency:'+r.id})),
 ...(linked.courses.records.value.find(r=>(r.contractKey??r.code)===line.value?.course)?.details?.extras??[]).filter(dateMatches).map((r:any,i:number)=>({...r,id:'course:'+i,priceType:r.type})),
]);
const headerFields=computed<FormField[]>(()=>[
 {key:'title',label:'Teklif Adı',required:true},{key:'createDate',label:'Kayıt Tarihi',type:'date',required:true,readonly:true},{key:'optionDate',label:'Opsiyon Tarihi',type:'date'},
 {key:'agency',label:'Acente',options:linked.agencyChoices.value,required:!draft.value?.sourceId},{key:'status',label:'Durum',options:simple(proposalStatuses),required:true},...(props.kind==='golf'?[]:[{key:'creator',label:'Oluşturan',readonly:true}]),
]);
const lineFields=computed<FormField[]>(()=>{
 if(!line.value)return [];const golf=line.value.category==='golf',combined=line.value.category==='hotel-golf';
 const f:FormField[]=[{key:'firstDate',label:golf?'İlk Oyun Tarihi':'Giriş Tarihi',type:'date',required:true},{key:'lastDate',label:golf?'Son Oyun Tarihi':'Çıkış Tarihi',type:'date',required:true},{key:'hotel',label:'Otel',options:linked.hotelChoices.value,required:!golf}];
 if(golf)f.push({key:'course',label:'Golf Sahası',options:linked.courseChoices.value,required:true},{key:'rounds',label:'Round',options:simple(['1','2','3','4','5','6','7','8','9','10','UNLIMITED']),required:true},{key:'teeTime',label:'Tee Time',type:'time'},{key:'priceType',label:'Saha Fiyat Tipi',options:simple(['TOHG','TO-OHG','RRHG','RR-OHG'])},{key:'golfContract',label:'Geçerli Golf Kontratı',options:golfTariffs.value.map(r=>({id:r.id,name:`${r.game} / ${r.name} / ${r.contractType} / ${r.currency}`}))},{key:'agencyPriceType',label:'Acente Fiyat Tipi',options:simple(['TOHG','TO-OHG','RRHG','RR-OHG'])},{key:'freeStatus',label:'Ücretsiz Hizmetler',options:simple(['HANDLING','TRANSFER','EXTRAS']),multiple:true});
 else f.push({key:'citizen',label:'Uyruk',options:options(citizens.records.value)},{key:'market',label:'Pazar',options:options(markets.records.value)},{key:'subMarket',label:'Alt Pazar'},{key:'board',label:'Pansiyon',options:options(linked.boards.records.value),required:true},{key:'roomType',label:'Oda Tipi',options:options(linked.rooms.records.value),required:true},{key:'roomName',label:'Oda Adı',options:options(roomOptions.value),required:true},{key:'accommodation',label:'Konaklama',options:simple(['SNG','DBL','TRP','ADD']),required:true},{key:'hotelContract',label:'Geçerli Otel Kontratı',options:options(hotelContracts.value)});
 if(combined)f.push({key:'rounds',label:'Golf Round',options:simple(['1','2','3','4','5','6','7','UNLIMITED'])},{key:'packageId',label:'Geçerli Golf Paketi',options:options(packages.value)});
 if(!golf)f.push({key:'tariffId',label:combined?'Paket Fiyat Satırı':'Oda Fiyat Satırı',options:prices.value.map((r:any)=>({id:r.id,name:`${r.accommodation} ${r.courseKey?courseName(r.courseKey):''} ${r.rounds??''} / ${r.price} ${r.currency}`}))},{key:'hotelAllotment',label:'Otel Allotment',type:'checkbox'},{key:'hotelGuarantee',label:'Otel Garanti',type:'checkbox'},{key:'agencyAllotment',label:'Acente Allotment',type:'checkbox'},{key:'agencyGuarantee',label:'Acente Garanti',type:'checkbox'});
 f.push({key:'pax',label:'Kişi',type:'number',min:1,max:10000,required:true},{key:'freePax',label:'Ücretsiz Kişi',type:'number',min:0,max:Number(line.value.pax),required:true});
 if(!golf)f.push({key:'rooms',label:'Oda Sayısı',type:'number',min:1,max:10000,required:true},{key:'infants',label:'Bebek',type:'number',min:0,max:10000},{key:'children',label:'Çocuk',type:'number',min:0,max:10000});
 f.push({key:'extraIds',label:'Ek Hizmetler',options:extraOptions.value.map(r=>({id:r.id,name:`${r.description} (${r.currency})`})),multiple:true}, {key:'handling',label:'Handling',options:extraOptions.value.map(r=>({id:r.id,name:r.description}))},{key:'transfer',label:'Transfer',options:extraOptions.value.map(r=>({id:r.id,name:r.description}))},{key:'note',label:'Açıklama',type:'textarea'});
 return f;
});
const moneyFields:FormField[]=[{key:'basis',label:'Fiyatın Uygulanması',required:true,options:[{id:'PERSON',name:'Ücretli kişi başına'},{id:'PERSON_NIGHT',name:'Ücretli kişi × gece'},{id:'ROOM_NIGHT',name:'Oda × gece'},{id:'FIXED',name:'Satır toplamı'}]},{key:'buyPrice',label:'Alış Bedeli',type:'number',min:0,step:'0.0001'},{key:'buyCurrency',label:'Alış Para Birimi',options:simple(currencyCodes),required:true},{key:'sellPrice',label:'Satış Bedeli',type:'number',min:0,step:'0.0001'},{key:'sellCurrency',label:'Satış Para Birimi',options:simple(currencyCodes),required:true},{key:'buyExtras',label:'Ek Hizmet Toplamı (Alış)',type:'number',min:0,step:'0.0001'},{key:'sellExtras',label:'Ek Hizmet Toplamı (Satış)',type:'number',min:0,step:'0.0001'}];
const rows=computed(()=>store.records.value.filter(r=>(filter.value==='all'||filter.value==='cancelled'?filter.value==='all'||r.status==='CANCELLED':filter.value==='options'?r.status!=='CANCELLED'&&!!r.optionDate&&r.optionDate<=today():r.status!=='CANCELLED')&&[r.title,agencyName(r.agency),r.creator].join(' ').toLocaleLowerCase('tr-TR').includes(query.value.toLocaleLowerCase('tr-TR'))));
function edit(r?:Proposal){draft.value=r?JSON.parse(JSON.stringify(r)):newProposal(props.userName);line.value=null;message.value='';}
function editLine(r?:ProposalLine,category:ProposalKind=props.kind){line.value=r?JSON.parse(JSON.stringify(r)):newProposalLine(category);message.value='';}
function changed(key:string){if(!line.value)return;const l=line.value;if(key==='hotel'){l.roomName='';l.hotelContract='';l.packageId='';l.tariffId='';l.extraIds=[];}if(key==='roomType')l.roomName='';if(['course','firstDate','lastDate'].includes(key)){l.golfContract='';l.hotelContract='';l.packageId='';l.tariffId='';}if(['hotelContract','packageId','accommodation'].includes(key))l.tariffId='';if(['hotel','course','firstDate','lastDate','roomType','roomName','accommodation','golfContract','hotelContract','packageId','tariffId','priceType'].includes(key)){l.buyPrice='';l.sellPrice='';}message.value='';}
function takePrice(){
 if(!line.value)return;const l=line.value;let price:any,kind='BUY';
 if(l.category==='golf'){const c=golfTariffs.value.find(r=>r.id===l.golfContract);if(c){const key=({'TOHG':'toHg','TO-OHG':'toOhg','RRHG':'rrHg','RR-OHG':'rrOhg'} as const)[l.priceType as 'TOHG'];price={price:c[key],currency:c.currency};kind=c.contractType;}}
 else {price=prices.value.find(r=>r.id===l.tariffId);kind=l.category==='hotel'?hotelContract.value?.contractType??'BUY':'BUY';}
 if(!price||price.price===''){message.value='Uygun bir tarife satırı seçin. Eksik fiyat otomatik oluşturulmaz.';return;}
 const side=kind==='SELL'?'sell':'buy';l[side+'Price' as 'buyPrice']=String(price.price);l[side+'Currency' as 'buyCurrency']=price.currency;
 message.value='Tarife bedeli alındı. Fiyatın uygulanmasını ve kontratın çocuk, indirim, ücretsiz kişi ve paket koşullarını kontrol edin; bu koşullar otomatik uygulanmaz.';
}
function takeExtras(){if(!line.value)return;const l=line.value;const ids=[...new Set([...l.extraIds,l.handling,l.transfer].filter(Boolean))];const selected=extraOptions.value.filter(r=>ids.includes(r.id));if(selected.length!==ids.length){message.value='Seçilen hizmetlerden biri artık geçerli değil.';return;}let buy=0,sell=0;for(const r of selected){if(r.currency!==l.buyCurrency||r.currency!==l.sellCurrency){message.value='Ek hizmet para birimleri farklı. Kur dönüşümü yapıp toplamları elle girin.';return;}const count=r.priceType==='PP'?Number(l.pax)-(l.freeStatus.includes('EXTRAS')?Number(l.freePax):0):r.priceType==='PROOM'?Number(l.rooms):r.priceType==='FIX'?1:null;if(count===null){message.value='Bu hizmetin fiyat uygulaması tanımlı değil; toplamı elle girin.';return;}buy+=Number(r.buyPrice)*count;sell+=Number(r.sellPrice)*count;}
 l.buyExtras=buy.toFixed(2);l.sellExtras=sell.toFixed(2);message.value='Ek hizmet toplamları alındı. Bebek/çocuk fiyatları ve ücretsiz handling/transfer koşulları ayrıca kontrol edilmelidir.';}
function addLine(){if(!line.value||!draft.value||!form.value?.reportValidity())return;const l=JSON.parse(JSON.stringify(line.value)) as ProposalLine;if(l.lastDate<l.firstDate||l.category!=='golf'&&nightsBetween(l.firstDate,l.lastDate)<1){message.value='Tarih aralığını kontrol edin.';return;}draft.value.lines=draft.value.lines.some(r=>r.id===l.id)?draft.value.lines.map(r=>r.id===l.id?l:r):[...draft.value.lines,l];line.value=null;message.value='';}
async function save(){if(!draft.value)return;if(line.value){message.value='Önce düzenlenen satırı ekleyin veya vazgeçin.';return;}if(!draft.value.lines.length&&!draft.value.sourceId){message.value='En az bir teklif satırı ekleyin.';return;}const r=JSON.parse(JSON.stringify(draft.value));if(await store.commit(store.records.value.some(v=>v.id===r.id)?store.records.value.map(v=>v.id===r.id?r:v):[...store.records.value,r]))draft.value=null;}
async function remove(r:Proposal){if(await voxConfirm(`${r.title} teklifi silinsin mi?`))await store.commit(store.records.value.filter(v=>v.id!==r.id));}
async function changeStatus(r:Proposal,event:Event){
 const select=event.target as HTMLSelectElement,status=select.value;
 if(status===r.status)return;
 message.value='';
 if(proposalStatuses.includes(status)&&await store.commit(store.records.value.map(v=>v.id===r.id?{...v,status}:v)))message.value=`${r.title}: durum ${status} olarak kaydedildi.`;
 select.value=store.records.value.find(v=>v.id===r.id)?.status??r.status;
}
function totalText(lines:ProposalLine[],side:string){return Object.entries(proposalTotals(lines,side)).map(([c,v]:any)=>`${v.amount.toFixed(2)} ${c}${v.incomplete?' + eksik fiyat':''}`).join(' · ')||'—';}
function exportRow(r:Proposal){const csv=[['Teklif',r.title],['Acente',agencyName(r.agency)],['Durum',r.status],['Tür','İlk Tarih','Son Tarih','Otel','Saha','Kişi','Alış','Para Birimi','Satış','Para Birimi'],...r.lines.map(l=>[l.category,l.firstDate,l.lastDate,hotelName(l.hotel),courseName(l.course),l.pax,lineAmount(l,'buy')??'',l.buyCurrency,lineAmount(l,'sell')??'',l.sellCurrency]),...(r.sourceTables??[]).flat()];const quote=(v:any)=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';const blob=new Blob(['\uFEFF'+csv.map(a=>a.map(quote).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='teklif.csv';a.click();URL.revokeObjectURL(url);}
</script>
<template><section class="proposals-module" :aria-label="title">
<header><h2>{{title}}<span v-if="draft&&kind==='golf'" class="creator-heading"> · Oluşturan: {{draft.creator}}</span></h2><template v-if="!draft"><button :disabled="!store.ready.value||store.busy.value" @click="edit()">＋ Yeni Teklif</button><input v-model="query" type="search" aria-label="Teklif ara" placeholder="Teklif, acente veya oluşturan"><select v-model="filter" aria-label="Teklif filtresi"><option value="active">Aktif Teklifler</option><option value="all">Tümü</option><option value="cancelled">İptal Edilenler</option><option value="options">Opsiyon Tarihi Gelenler</option></select></template><button v-else @click="draft=null;line=null">← Listeye Dön</button></header>
<p v-if="store.storageError.value" role="alert">{{store.storageError.value}}</p><p v-if="message" role="status">{{message}}</p>
<div class="body"><template v-if="!draft"><table><thead><tr><th>Kayıt Tarihi</th><th>Opsiyon</th><th>Teklif Adı</th><th>Acente</th><th>Oluşturan</th><th>Durum</th><th>İşlem</th></tr></thead><tbody><tr v-for="r in rows" :key="r.id"><td>{{r.createDate}}</td><td>{{r.optionDate||'—'}}</td><td>{{r.title}}</td><td>{{agencyName(r.agency)||'—'}}</td><td>{{r.creator}}</td><td><select class="status-select" :aria-label="r.title+' durumu'" :value="r.status" :disabled="!store.ready.value||store.busy.value" @change="changeStatus(r,$event)"><option v-for="status in proposalStatuses" :key="status" :value="status">{{status}}</option></select></td><td class="actions"><VoxActionButton action="edit" :aria-label="r.title+' düzenle'" @click="edit(r)"/><button class="export" :aria-label="r.title+' dışa aktar'" title="CSV dışa aktar" @click="exportRow(r)">⇩</button><VoxActionButton action="delete" :disabled="store.busy.value" @click="remove(r)"/></td></tr><tr v-if="!rows.length"><td colspan="7">{{store.busy.value?'Yükleniyor…':'Teklif bulunamadı.'}}</td></tr></tbody></table></template>
<form v-else ref="form" @submit.prevent="save"><ProposalFields :row="draft" :fields="headerFields"/><label class="notes">Teklif Notu<textarea v-model="draft.note" maxlength="5000"/></label>
<div class="line-buttons"><button v-if="kind!=='hotel'" type="button" @click="editLine(undefined,'golf')">＋ {{kind==='hotel-golf'?'Ek Golf':'Golf Satırı'}}</button><button v-if="kind!=='golf'" type="button" @click="editLine(undefined,'hotel')">＋ {{kind==='hotel-golf'?'Ek Oda':'Otel Satırı'}}</button><button v-if="kind==='hotel-golf'" type="button" @click="editLine(undefined,'hotel-golf')">＋ Golf Paketi</button></div>
<fieldset v-if="line"><legend>{{line.category==='golf'?'Golf':line.category==='hotel'?'Otel':'Otel + Golf'}} Satırı</legend><ProposalFields :row="line" :fields="lineFields" @change="changed"/><p v-if="line.category!=='golf'">Gece: {{nightsBetween(line.firstDate,line.lastDate)}}</p><div class="line-buttons"><button type="button" @click="takePrice">Seçili Tarife Bedelini Al</button><button type="button" @click="takeExtras">Seçili Ek Hizmetleri Topla</button></div><ProposalFields :row="line" :fields="moneyFields"/><p>Alış: {{lineAmount(line,'buy')??'Fiyat bekleniyor'}} {{line.buyCurrency}} · Satış: {{lineAmount(line,'sell')??'Fiyat bekleniyor'}} {{line.sellCurrency}}</p><small>Bedel boşsa fiyat beklenir. Farklı para birimleri ayrı toplanır; kur dönüşümü, indirim ve çocuk fiyatları otomatik uygulanmaz.</small><div class="line-buttons"><button type="button" @click="addLine">Satırı Ekle / Güncelle</button><button type="button" @click="line=null">Satırdan Vazgeç</button></div></fieldset>
<h3>Teklif Satırları</h3><div class="table-scroll"><table><thead><tr><th>Tür</th><th>Tarih</th><th>Otel / Saha</th><th>Kişi</th><th>Oda</th><th>Alış</th><th>Satış</th><th>İşlem</th></tr></thead><tbody><tr v-for="r in draft.lines" :key="r.id"><td>{{r.category==='golf'?'Golf':r.category==='hotel'?'Otel':'Otel + Golf'}}</td><td>{{r.firstDate}} — {{r.lastDate}}</td><td>{{hotelName(r.hotel)}} {{courseName(r.course)}}</td><td>{{r.pax}} / Ücretsiz: {{r.freePax}}</td><td>{{r.category==='golf'?'—':r.rooms}}</td><td>{{lineAmount(r,'buy')??'Bekleniyor'}} {{r.buyCurrency}}</td><td>{{lineAmount(r,'sell')??'Bekleniyor'}} {{r.sellCurrency}}</td><td class="actions"><VoxActionButton action="edit" @click="editLine(r)"/><VoxActionButton action="delete" @click="draft.lines=draft.lines.filter(l=>l.id!==r.id)"/></td></tr></tbody></table></div>
<div v-if="draft.sourceTables?.length" class="source-tables"><h3>Kaynak Teklif Dökümü</h3><p>Kaynakta görünen fiyat ve boş alanlar korunmuştur. Bu geçmiş satırlar yeniden fiyatlandırılmamıştır.</p><div v-for="(table,i) in draft.sourceTables" :key="i" class="table-scroll"><table><thead><tr><th v-for="(cell,c) in table[0]" :key="c">{{cell}}</th></tr></thead><tbody><tr v-for="(row,j) in table.slice(1)" :key="j"><td v-for="(cell,c) in row" :key="c">{{cell}}</td></tr></tbody></table></div></div>
<footer>Alış: {{totalText(draft.lines,'buy')}}<br>Satış: {{totalText(draft.lines,'sell')}}<div class="line-buttons"><button type="submit" :disabled="store.busy.value">Teklifi Kaydet</button><button type="button" @click="draft=null;line=null">Vazgeç</button><button type="button" @click="exportRow(draft)">CSV Dışa Aktar</button></div></footer></form></div><footer v-if="!draft">Toplam teklif: {{store.records.value.length}} · Gösterilen: {{rows.length}}</footer></section></template>
<style scoped>
.proposals-module{height:100%;min-height:0;display:flex;flex-direction:column;background:#f7fbfe;color:#254f6c;font:12px Tahoma,sans-serif}header{display:flex;align-items:center;gap:10px;flex-wrap:wrap;padding:12px;border-bottom:1px solid #cadde9}.creator-heading{font-size:12px;font-weight:normal;margin-left:10px}h2{font-size:16px;margin:0 auto 0 0}button,input,select,textarea{font:12px Tahoma,sans-serif}button{padding:7px 10px;background:#e7f3fb;border:1px solid #8cb2cb;color:#24577d;cursor:pointer}button:disabled{opacity:.5;cursor:default}header input,header select{height:30px;border:1px solid #8cb2cb;padding:5px;color:#24577d;background:white}.body{flex:1;min-height:0;overflow:auto}form{padding:15px}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid #d7e4ed;text-align:left}th{background:#e4f0f9}tbody tr:nth-child(even){background:#edf5fb}.status-select{min-width:125px;height:30px;border:1px solid #8cb2cb;padding:4px;color:#24577d;background:white}.actions{white-space:nowrap}.actions button+button{margin-left:6px}.export{border-radius:50%;width:26px;height:26px;padding:0}.line-buttons{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}fieldset{background:#eaf4fb;border:1px solid #bdd5e7;padding:12px}.table-scroll{overflow:auto;margin:10px 0}.notes{display:flex;flex-direction:column;gap:5px;margin-top:12px}textarea{border:1px solid #8cb2cb;min-height:45px;padding:6px}footer{padding:12px;border-top:1px solid #cadde9;line-height:1.7}[role=alert]{color:#a32c20;padding:10px}[role=status]{background:#fff1d3;color:#6b4c13;margin:0;padding:10px}small{color:#6b4c13}.source-tables{margin-top:20px}h3{font-size:14px}
</style>
